language: python
cache: pip
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
  - git fetch origin --depth=1 main:main
  - pip install -e '.[test]'
script: pytest
